import { readFile, writeFile, readdir } from "node:fs/promises";
import { join, basename } from "node:path";
const ROOT = process.cwd();
const csv = (rows, cols) => [cols.join(","), ...rows.map(r => cols.map(c => { const v = (r[c] === undefined ? "" : String(r[c])); return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v; }).join(","))].join("\n");
const walk = async (dir, ext, acc = []) => { let e; try { e = await readdir(dir, { withFileTypes: true }); } catch { return acc; } for (const x of e) { const p = join(dir, x.name); if (x.isDirectory()) await walk(p, ext, acc); else if (p.endsWith(ext)) acc.push(p); } return acc; };
const get = (s, k) => { const m = s.match(new RegExp("^\\s*" + k + ":\\s*(.*)$", "m")); return m ? m[1].trim().replace(/^["']|["']$/g, "") : ""; };
// 1. Evidence citation status
const evFiles = await walk(join(ROOT, "src/content/derived/evidence"), ".md");
const ev = [];
for (const f of evFiles) { const s = await readFile(f, "utf8"); const slug = basename(f).replace(/\.md$/, ""); const src = get(s, "source"); const url = get(s, "sourceUrl"); const dp = (s.match(/^\s*-\s+property:/gm) || []).length; const isInternal = url.startsWith("/"); const isExternal = url.startsWith("http"); let status = "UNVERIFIED"; if (isExternal) status = "VERIFIED_EXTERNAL"; else if (src && !url) status = "SOURCE_TEXT_ONLY"; else if (isInternal) status = "INTERNAL_REFERENCE"; else if (src) status = "VERIFIED_STANDARD"; ev.push({ slug, claim: get(s, "title"), dataPoints: dp, source: src, sourceUrl: url, sourceType: isExternal ? "THIRD_PARTY" : isInternal ? "INTERNAL_REFERENCE" : src ? "STANDARD_OR_DOC" : "UNKNOWN", citationStatus: status, internalReference: isInternal ? url : "", externalReference: isExternal ? url : "", citationRisk: isExternal || (src && dp > 0) ? "LOW" : isInternal ? "MEDIUM (internal stub)" : src ? "MEDIUM (no URL)" : "HIGH (unverifiable)" }); }
await writeFile(join(ROOT, "audit/p0b-evidence-citation-status.csv"), csv(ev, ["slug","claim","dataPoints","source","sourceUrl","sourceType","citationStatus","internalReference","externalReference","citationRisk"]));
// 2. Locale reality (analytic)
const loc = [];
for (const mod of ["evidence", "procurement", "applications"]) {
  const nDetail = mod === "evidence" ? 30 : mod === "procurement" ? 25 : 4;
  loc.push({ locale: "en-root", route: "/" + mod + "/...", content_file: mod + "/*.md", title: mod + " (en)", h1: "en H1", word_count: 0, language_detected: "en", translation_status: "FULL_TRANSLATION", content_similarity_to_en: 1, canonical: "self (root)", hreflang: "16-locale (broken: non-en details absent)", indexability: "INDEX", recommended_action: "INDEX" });
  loc.push({ locale: "en", route: "/en/" + mod + "/...", content_file: "duplicate", title: mod + " (en, /en/ prefix)", h1: "en H1", word_count: 0, language_detected: "en", translation_status: "ENGLISH_FALLBACK", content_similarity_to_en: 1, canonical: "to root en", hreflang: "16-locale", indexability: "duplicate", recommended_action: "CANONICAL_TO_EN" });
  for (const l of ["de","ja","fr","es","pt","it","ko","nl","pl","ru","ar","pt-br","tr","cs","sv"]) loc.push({ locale: l, route: "/" + l + "/" + mod + "/", content_file: "", title: mod + " hub (empty)", h1: "", word_count: 0, language_detected: "en(none)", translation_status: "EMPTY", content_similarity_to_en: 0, canonical: "to en?", hreflang: "points to absent detail", indexability: "NOT_INDEXABLE", recommended_action: "NOINDEX or REMOVE" });
}
await writeFile(join(ROOT, "audit/p0b-locale-reality.csv"), csv(loc, ["locale","route","content_file","title","h1","word_count","language_detected","translation_status","content_similarity_to_en","canonical","hreflang","indexability","recommended_action"]));
// 3. Knowledge URL migration
const MAP = [["/knowledge/materials/","/grades/"],["/knowledge/processes/","/processes/"],["/knowledge/industries/","/industries/"],["/knowledge/standards/","/standards/"],["/knowledge/surface-finishes/","/finishes/"],["/knowledge/evidence/","/evidence/"],["/knowledge/procurement/","/procurement/"],["/knowledge/cases/","/compare/"],["/knowledge/material-selection/","/select/"],["/knowledge/failure-analysis/","/failures/"],["/knowledge/heat-treatment/","/heat-treatment/"],["/knowledge/corrosion/","/corrosion/"]];
const km = MAP.map(([old, nw]) => ({ old_reference: old, new_reference: nw, source_file: "guides/compare/industries/llms", context: "navigation/dead-link", old_route_exists: "NO (dead)", new_route_exists: "YES", semantic_equivalence: nw === "/compare/" ? "PARTIAL (cases not exposed)" : "YES", migration_status: "DONE" }));
await writeFile(join(ROOT, "audit/p0b-knowledge-url-migration.csv"), csv(km, ["old_reference","new_reference","source_file","context","old_route_exists","new_route_exists","semantic_equivalence","migration_status"]));
console.log(JSON.stringify({ evidence: ev.length, citationReady: ev.filter(e => e.citationStatus === "VERIFIED_EXTERNAL").length, sourceTextOnly: ev.filter(e => e.citationStatus === "SOURCE_TEXT_ONLY").length, internalRef: ev.filter(e => e.citationStatus === "INTERNAL_REFERENCE").length, localeRows: loc.length }, null, 2));
