import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, extname, basename } from "node:path";
const ROOT = process.cwd();
const OUT = join(ROOT, "audit");
const walk = async (dir, ext) => { const acc = []; const step = async (d) => { let ents; try { ents = await readdir(d, { withFileTypes: true }); } catch { return; } for (const e of ents) { const p = join(d, e.name); if (e.isDirectory()) await step(p); else if (!ext || ext.includes(extname(e.name))) acc.push(p); } }; await step(dir); return acc; };
function parseFrontmatter(src) { const m = src.match(/^---\s*\r?\n([\s\S]*?)\r?\n---/); if (!m) return { data: {}, body: src }; const data = {}; let curKey = null; for (const raw of m[1].split(/\r?\n/)) { const line = raw.replace(/\r$/, ""); if (!line.trim()) continue; const indent = (line.match(/^\s*/)[0] || "").length; const list = line.match(/^(\s*)- +(.*)$/); const kv = line.match(/^(\s*)([A-Za-z0-9_-]+):\s*(.*)$/); if (list && curKey && indent > 0) { if (!Array.isArray(data[curKey])) data[curKey] = []; data[curKey].push(list[2].replace(/^["']|["']$/g, "")); continue; } if (kv) { const key = kv[2]; const val = kv[3].trim(); if (indent === 0) { curKey = key; if (val === "") data[key] = []; else data[key] = val.replace(/^["']|["']$/g, ""); continue; } if (curKey && Array.isArray(data[curKey])) { data[curKey] = {}; data[curKey][key] = val === "" ? [] : val.replace(/^["']|["']$/g, ""); } else if (curKey && typeof data[curKey] === "object" && !Array.isArray(data[curKey])) { data[curKey][key] = val === "" ? [] : val.replace(/^["']|["']$/g, ""); } continue; } } return { data, body: src.slice(m[0].length) }; }
function wc(body) { return (body.replace(/^#{1,6}\s*/gm, "").match(/[A-Za-z0-9\u00C0-\u024F'\-.%\/]+/g) || []).length; }
const countTables = (body) => (body.match(/^\|/gm) ? new Set(body.match(/^\|/gm)).size : 0);
const countMdLinks = (body) => (body.match(/\[([^\]]+)\]\(([^)]+)\)/g) || []).length;
const hasSection = (body, re) => new RegExp(re, "i").test(body);
const collections = { materials: { dir: "src/content/core/materials", kind: "Material", route: "/grades/" }, processes: { dir: "src/content/core/processes", kind: "Process", route: "/processes/" }, industries: { dir: "src/content/core/industries", kind: "Industry", route: "/industries/" }, standards: { dir: "src/content/core/standards", kind: "Standard", route: "/standards/" }, surfaceFinishes: { dir: "src/content/core/surface-finishes", kind: "Finish", route: "/finishes/" }, materialSelection: { dir: "src/content/core/material-selection", kind: "SelectionGuide", route: "/select/" }, failureAnalysis: { dir: "src/content/core/failure-analysis", kind: "FailureMode", route: "/failures/" }, heatTreatment: { dir: "src/content/core/heat-treatment", kind: "Process", route: "/heat-treatment/" }, corrosion: { dir: "src/content/core/corrosion", kind: "Corrosion", route: "/corrosion/" }, evidence: { dir: "src/content/derived/evidence", kind: "Evidence", route: "/evidence/" }, comparisons: { dir: "src/content/derived/comparisons", kind: "Comparison", route: "/compare/" }, procurement: { dir: "src/content/derived/procurement", kind: "Procurement", route: "/procurement/" }, guides: { dir: "src/content/derived/guides", kind: "Guide", route: "/guides/" }, cases: { dir: "src/content/derived/cases", kind: "CaseStudy", route: "/cases/" }, applications: { dir: "src/content/applications", kind: "Application", route: "/applications/" }, blog: { dir: "src/content/site/blog", kind: "Blog", route: "/blog/" }, faqs: { dir: "src/content/site/faqs", kind: "FAQ", route: "/faq/" } };
const renderedInPages = new Set(["pages","settings","docs","materials","processes","industries","standards","surfaceFinishes","materialSelection","failureAnalysis","heatTreatment","corrosion","comparisons","guides","faqs","blog"]);
const rows = []; const entityOcc = {}; const kgEdges = new Map();
for (const [coll, cfg] of Object.entries(collections)) { const files = await walk(join(ROOT, cfg.dir), [".md", ".mdx", ".json"]); for (const f of files) { const raw = await readFile(f, "utf8"); const { data, body } = parseFrontmatter(raw); const rel = f.slice(ROOT.length + 1); const slug = basename(f).replace(/\.(md|mdx|json)$/, ""); const row = { collection: coll, kind: cfg.kind, slug, file: rel, locale: data.locale || "en", title: data.title || slug, route: (data.slug ? `${cfg.route}${String(data.slug).split("/")[0]}/` : `${cfg.route}${slug}/`), words: wc(body), tables: countTables(body), mdLinks: countMdLinks(body), quickAnswer: hasSection(body, "quick answer|tl;dr|tldr") || !!data.quickAnswer, properties: !!data.properties, dataPoints: !!data.dataPoints, faqs: !!data.faqs, checklist: !!data.checklist, source: !!data.source, sourceUrl: !!data.sourceUrl, entities: [] }; const relArr = (k) => Array.isArray(data[k]) ? data[k] : []; const related = [...relArr("materials"), ...relArr("processes"), ...relArr("industries"), ...relArr("standards"), ...relArr("finishes"), ...relArr("certifications"), ...relArr("relatedMaterials"), ...relArr("relatedProcesses"), ...relArr("relatedStandards"), ...relArr("relatedServices"), ...relArr("relatedEntities"), ...relArr("relatedEvidence"), ...relArr("relatedComparisons"), ...relArr("equipment")]; row.relatedEntityCount = related.length; for (const r of new Set(related)) { entityOcc[r] = entityOcc[r] || { count: 0, pages: new Set() }; entityOcc[r].count++; entityOcc[r].pages.add(`${coll}:${slug}`); row.entities.push(r); kgEdges.set(`${coll}:${slug}|related_to|${r}`, 1); } if (data.entityA && data.entityB) { row.entityA = data.entityA; row.entityB = data.entityB; } rows.push(row); } }
await mkdir(OUT, { recursive: true });
await writeFile(join(OUT, "raw-data.json"), JSON.stringify({ generatedAt: new Date().toISOString(), renderedCollections: [...renderedInPages].sort(), allCollections: Object.keys(collections), contentFileCount: rows.length, entries: rows }, null, 2));
console.log("scan ok");
