#!/usr/bin/env node
/**
 * qa-report.mjs — QA report generator for translation batches.
 *
 * Generates reports/qa-{locale}-{batch}.md with per-file and summary results.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..");
const REPORTS_DIR = resolve(ROOT, "reports");

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Generate a QA report file.
 * @param {object} opts
 * @param {string} opts.locale - Target locale
 * @param {string} [opts.batch="batch-1"] - Batch identifier
 * @param {Array<{file:string, qaResult:object, passed:boolean}>} opts.results - Per-file QA results
 * @param {object} [opts.stats] - Optional reporter stats
 * @returns {string} - Path to generated report
 */
export function generateReport({ locale, batch = "batch-1", results, stats }) {
  const totalFiles = results.length;
  const passed = results.filter((r) => r.passed).length;
  const failed = results.filter((r) => !r.passed).length;
  const withWarnings = results.filter((r) => {
    if (r.passed) return false;
    return Object.values(r.qaResult?.checks || {}).some((c) => c.fail);
  }).length;

  const lines = [];
  lines.push(`# QA Report: ${locale}-${batch}`);
  lines.push(`- **Date**: ${new Date().toISOString().split("T")[0]}`);
  lines.push("");
  lines.push("## Summary");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total files | ${totalFiles} |`);
  lines.push(`| Passed | ${passed} |`);
  lines.push(`| Failed | ${failed} |`);
  lines.push(`| With warnings | ${withWarnings} |`);
  lines.push("");

  // Stats from reporter
  if (stats) {
    lines.push(`| Translated | ${stats.done} |`);
    lines.push(`| Skipped | ${stats.skipped} |`);
    lines.push(`| Errors | ${stats.failed} |`);
    lines.push(`| Tokens used | ${stats.totalTokens} |`);
    lines.push(`| Duration | ${((stats.endTime - stats.startTime) / 1000).toFixed(1)}s |`);
    lines.push("");
  }

  // Failed files
  const failedFiles = results.filter((r) => !r.passed);
  if (failedFiles.length > 0) {
    lines.push("## Failed Files");
    lines.push("");
    for (const f of failedFiles) {
      lines.push(`### ${f.file}`);
      lines.push("");
      for (const [checkName, checkResult] of Object.entries(f.qaResult?.checks || {})) {
        if (checkResult.fail) {
          lines.push(`**${checkName}**: ${checkResult.items.length} issue(s)`);
          for (const item of checkResult.items) {
            lines.push(`- [${item.type}] ${item.message}`);
          }
          lines.push("");
        }
      }
    }
  }

  // All checks summary
  lines.push("## Check Distribution");
  lines.push("");
  const checkCounts = {};
  for (const f of results) {
    for (const [checkName, checkResult] of Object.entries(f.qaResult?.checks || {})) {
      if (!checkCounts[checkName]) checkCounts[checkName] = { pass: 0, fail: 0, totalItems: 0 };
      if (checkResult.fail) {
        checkCounts[checkName].fail++;
        checkCounts[checkName].totalItems += checkResult.items.length;
      } else {
        checkCounts[checkName].pass++;
      }
    }
  }
  lines.push(`| Check | Pass | Fail | Issues |`);
  lines.push(`|-------|------|------|--------|`);
  for (const [name, counts] of Object.entries(checkCounts)) {
    lines.push(`| ${name} | ${counts.pass} | ${counts.fail} | ${counts.totalItems} |`);
  }
  lines.push("");

  lines.push("---");
  lines.push(`*Generated by QA Gate v1.0 | ${new Date().toISOString()}*`);

  const report = lines.join("\n");
  const reportPath = resolve(REPORTS_DIR, `qa-${locale}-${batch}.md`);

  mkdirSync(REPORTS_DIR, { recursive: true });
  writeFileSync(reportPath, report, "utf8");

  console.log(`[qa-report] Generated: ${reportPath}`);
  return reportPath;
}

export default { generateReport };