import { writeFileSync } from "node:fs";
const code = [
'#!/usr/bin/env node',
'/**',
' * translator.mjs --- Translation API client (OpenAI-compatible).',
' * Supports DeepSeek and Sensenova.',
' */',
'',
'import { readFileSync, existsSync } from "node:fs";',
'import { resolve, dirname } from "node:path";',
'import { fileURLToPath } from "node:url";',
'',
'const __dirname = dirname(fileURLToPath(import.meta.url));',
'const ROOT = resolve(__dirname, "..", "..");',
'',
'function loadCredentials() {',
'  const paths = [ resolve(ROOT, "secrets", ".env.translate"), resolve(ROOT, ".env") ];',
'  const vars = {};',
'  for (const p of paths) {',
'    if (!existsSync(p)) continue;',
'    const text = readFileSync(p, "utf8");',
'    for (const line of text.split("\\n")) {',
'      const t = line.trim();',
'      if (!t || t.startsWith("#")) continue;',
'      const eq = t.indexOf("=");',
'      if (eq === -1) continue;',
'      const k = t.slice(0, eq).trim();',
'      const v = t.slice(eq + 1).trim().replace(/^["\']|["\']$/g, "");',
'      vars[k] = v;',
'    }',
'  }',
'  if (process.env.DEEPSEEK_API_KEY) vars.DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY;',
'  if (process.env.SENSENOVA_API_KEY) vars.SENSENOVA_API_KEY = process.env.SENSENOVA_API_KEY;',
'  return vars;',
'}',
'',
'let _creds = null;',
'function getCredentials() {',
'  if (!_creds) _creds = loadCredentials();',
'  return _creds;',
'}',
'',
'function getProviderConfig() {',
'  const creds = getCredentials();',
'  if (creds.SENSENOVA_API_KEY) {',
'    return { apiKey: creds.SENSENOVA_API_KEY, baseURL: creds.SENSENOVA_BASE_URL || "https://api.sensenova.cn/v1", model: creds.SENSENOVA_MODEL || "sensenova-6.8-flash-lite", provider: "sensenova" };',
'  }',
'  return { apiKey: creds.DEEPSEEK_API_KEY, baseURL: creds.DEEPSEEK_BASE_URL || "https://api.deepseek.com/v1", model: creds.DEEPSEEK_MODEL || "deepseek-chat", provider: "deepseek" };',
'}',
'',
'export async function translate(opts) {',
'  const { system, messages, locale, onChunk, maxRetries } = opts;',
'  const cfg = getProviderConfig();',
'  if (!cfg.apiKey) throw new Error("No API key found");',
'  const url = cfg.baseURL.replace(/\\/+$/, "") + "/chat/completions";',
'  const body = { model: cfg.model, messages: [{ role: "system", content: system }, ...messages], temperature: 0.3, max_tokens: 8192, stream: typeof onChunk === "function" };',
'  let lastErr;',
'  for (let a = 1; a <= (maxRetries || 3); a++) {',
'    try {',
'      const res = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json", Authorization: "Bearer " + cfg.apiKey }, body: JSON.stringify(body) });',
'      if (!res.ok) { const errText = await res.text().catch(function() { return "unknown"; }); throw new Error("API " + res.status + ": " + errText.slice(0, 200)); }',
'      if (body.stream) {',
'        const reader = res.body.getReader(); const dec = new TextDecoder(); let buf = ""; let full = "";',
'        while (true) { const { done, value } = await reader.read(); if (done) break; buf += dec.decode(value, { stream: true }); const lns = buf.split("\\n"); buf = lns.pop() || "";',
'          for (const ln of lns) { const t = ln.trim(); if (!t || !t.startsWith("data: ")) continue; const d = t.slice(6); if (d === "[DONE]") break; try { const p = JSON.parse(d); const delta = p?.choices?.[0]?.delta?.content; if (delta) { full += delta; if (typeof onChunk === "function") onChunk(delta); } } catch {} } }',
'        return full;',
'      }',
'      const data = await res.json();',
'      const content = data?.choices?.[0]?.message?.content;',
'      if (!content) throw new Error("Empty response");',
'      return content;',
'    } catch (err) {',
'      lastErr = err;',
'      if (a < (maxRetries || 3)) { const delay = Math.min(1000 * Math.pow(2, a - 1), 30000); console.warn("  [t] retry " + a + ": " + err.message); await new Promise(function(r) { setTimeout(r, delay); }); }',
'    }',
'  }',
'  throw lastErr;',
'}',
'',
'export async function testConnection() {',
'  try {',
'    const cfg = getProviderConfig();',
'    if (!cfg.apiKey) return false;',
'    const res = await fetch(cfg.baseURL.replace(/\\/+$/, "") + "/models", { headers: { Authorization: "Bearer " + cfg.apiKey } });',
'    return res.ok;',
'  } catch { return false; }',
'}',
'',
'export function estimateTokens(text) {',
'  const cjk = (text.match(/[\\u4e00-\\u9fff\\u3040-\\u309f\\u30a0-\\u30ff\\uac00-\\ud7af]/g) || []).length;',
'  return Math.ceil(cjk / 2 + (text.length - cjk) / 4);',
'}',
'',
'export default { translate, testConnection, estimateTokens };',
].join('\n');
writeFileSync("scripts/lib/translator.mjs", code, "utf8");
console.log("Done");